// <auto-generated />
namespace DeviceCloud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Origin20160110 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Origin20160110));
        
        string IMigrationMetadata.Id
        {
            get { return "201601100653503_Origin20160110"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
